### ISSUE TITLE
[Bug] TKMM cannot be reinstalled (installer does not open)

### ISSUE THREAD

**Issue by ZachIsCool123321** [TKMM-Team/Tkmm#27]
tkmm.exe and tkmm-launcher.exe fail to open. I've deleted all folders related to the applications in appdata and documents. I'm not sure if my PC is the issue or if this is a tkmm problem [.NET is installed].

**Comment by ArchLeaders** [comment]
This is likely an issue with symlinks, this has been fixed in `master` but I have not released it yet. You can try running TKMM as admin or enabling developer mode. If this does not fix it, try deleting `%localappdata%\tkmm\Config.json` and make sure you do not have your merged export folder in the Ryujinx or yuzu mod folders.

**Comment by ZachIsCool123321** [comment]
> make sure you do not have your merged export folder in the Ryujinx or yuzu mod folders.

I deleted symlink before reinstalling so that may have been the issue.
unfortunately it is still not working but that's most likely my fault. Thank you though for the very fast response.

**Comment by ArchLeaders** [comment]
Should I close this issue, or are you still encountering the problem?

**Comment by ZachIsCool123321** [comment]
Was just writing that I found that the symlink returned and moving it fixed my issue, thank you so much!
(Issue can be closed.)
