### ISSUE TITLE
[Bug] Versioned SARC files are not renamed to the current game version.

### ISSUE THREAD

**Issue by ArchLeaders** [TKMM-Team/Tkmm#39]

**Comment by dt-12345** [comment]
Ideally, the AddressTable should be used to rename all versioned files found inside since the game will search it instead of using the game version to find the file it is looking for. Event flow, effect, and loose ainb files also have their own dedicated version control files which should be used in those cases (though there aren't any versioned ainb files in totk so it goes unused).

**Comment by ArchLeaders** [comment]
This issue only addresses sarc files, but yes; the general content merger should rename files to match the address table. I'll add that to the project todo list.
