### ISSUE TITLE
Uninstall button does not work on the selected mod (Profiles Page)

### ISSUE THREAD

**Issue by ArchLeaders** [TKMM-Team/Tkmm#5]
On the master mod list, the uninstall button cannot be clicked if the mod is selected.

## Recreate

- Install a mod
- Select it in the master mod collection (so it is highlighted)
- Attempt to uninstall (trash bin icon)
- Observe that nothing happens

**Comment by MasterBubbles** [comment]
For the uninstall button to work, click on a mod from the profile on the left column, then the trash button will work on the right column. The button doesn't work only if no mod is highlighted in the left column (under the currently selected profile).

It happens when you delete a mod from a profile before trying to delete it from TKMM completely

**Comment by MasterBubbles** [comment]
~~Ignore everything I said previously, it's when the mod is selected on the right column that its trash button no longer works~~
